function reportsPage(){
  const tabs=[['weekly','주간'],['monthly','월간'],['trend','추세'],['individual','개인'],['groups','순모임']];
  return `<section class="section"><div class="section-head"><h2>리포트</h2><div class="hint">화면 · Excel/CSV · 인쇄/PDF</div></div><div class="tabs">${tabs.map(([v,l])=>`<button class="tab ${ui.reportTab===v?'on':''}" data-report-tab="${v}">${l}</button>`).join('')}</div><div class="toolbar-row"><div class="seg"><button data-report-mode="summary" class="${ui.reportMode==='summary'?'on':''}">Summary</button><button data-report-mode="detail" class="${ui.reportMode==='detail'?'on':''}">Detailed</button></div><button class="btn" id="exportReport">Excel/CSV</button><button class="btn" id="printReport">PDF/인쇄</button>${isAdmin()?'<button class="btn" id="saveDrive">Save to Drive</button>':''}</div><div style="margin-top:8px">${reportContent()}</div></section>`;
}
function reportContent(){
  if(ui.reportTab==='weekly') return weeklyReport(); if(ui.reportTab==='monthly')return monthlyReport(); if(ui.reportTab==='trend')return trendReport(); if(ui.reportTab==='individual')return individualReport(); return groupReport();
}
function weeklyReport(){ const start=startOfWeek(ui.date),end=endOfWeek(ui.date),sessions=db.sessions.filter(s=>s.date>=start&&s.date<=end&&s.status==='Held'); const regUnique=new Set(); let guests=0,online=0; sessions.forEach(s=>{sessionAttendance(s.id).forEach(id=>regUnique.add(id));guests+=s.guestCount||0;online+=s.onlineCount||0;});return `<div class="grid three">${statCard(regUnique.size,'등록교인 Unique',`${start} ~ ${end}`,'main-number')}${statCard(guests,'Guest','합계')}${statCard(online,'Online','별도 집계')}</div><section class="section"><div class="section-head"><h2>모임별</h2></div><div class="row-list">${sessions.map(s=>{const m=meetingById(s.meetingId);return `<div class="row-card"><div class="mini-icon">✓</div><div class="row-main"><div class="row-title">${esc(s.nameOverride||m?.name||s.meetingId)}</div><div class="row-sub">${s.date} · Guest ${s.guestCount||0}${m?.online?' · Online '+(s.onlineCount||0):''}</div></div><div class="number" style="font-size:24px">${sessionAttendance(s.id).length}</div></div>`;}).join('')||'<div class="empty">이 주의 기록이 없습니다.</div>'}</div></section>${ui.reportMode==='detail'?detailedAbsenteeSection(sessions):''}`; }
function detailedAbsenteeSection(sessions){ const regular=activeMembers().filter(m=>classification(m,'sun2',ui.date)==='정기'); const present=new Set(sessions.filter(s=>s.meetingId==='sun2').flatMap(s=>sessionAttendance(s.id))); const absent=regular.filter(m=>!present.has(m.id)); return `<section class="section"><div class="section-head"><h2>정기 출석자 결석</h2><div class="hint">Note 미포함</div></div><div class="row-list">${absent.map(m=>`<div class="row-card"><div class="avatar">${esc(displayName(m)[0])}</div><div class="row-main"><div class="row-title">${esc(displayName(m))} ${esc(m.title)}</div><div class="row-sub">연속결석 ${consecutiveAbsences(m.id,'sun2',ui.date)}회</div></div></div>`).join('')||'<div class="empty">없음</div>'}</div></section>`; }
function monthlyReport(){ const month=monthKey(ui.date),sessions=db.sessions.filter(s=>s.date.startsWith(month)&&s.status==='Held'); const unique=new Set(sessions.flatMap(s=>sessionAttendance(s.id))); const guest=sessions.reduce((n,s)=>n+(s.guestCount||0),0),online=sessions.reduce((n,s)=>n+(s.onlineCount||0),0); return `<div class="grid three">${statCard(unique.size,'월 등록교인 Unique',month,'main-number')}${statCard(guest,'Guest','월 합계')}${statCard(online,'Online','월 합계')}</div><section class="section"><div class="section-head"><h2>모임별 월평균</h2></div><div class="row-list">${regularMeetings().map(m=>{const ss=sessions.filter(s=>s.meetingId===m.id),avg=ss.length?Math.round(ss.reduce((n,s)=>n+sessionAttendance(s.id).length,0)/ss.length):0;return `<div class="row-card"><div class="mini-icon">▤</div><div class="row-main"><div class="row-title">${esc(m.name)}</div><div class="row-sub">${ss.length}회 · 평균</div></div><div class="number" style="font-size:24px">${avg}</div></div>`;}).join('')}</div></section>`; }
function trendReport(){ const months=[]; for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);months.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);} return `<div class="card report-card"><div class="row-title">최근 6개월 등록교인 Unique 추세</div>${months.map((m,i)=>{const sessions=db.sessions.filter(s=>s.date.startsWith(m)),u=new Set(sessions.flatMap(s=>sessionAttendance(s.id))).size,pct=Math.max(8,Math.min(100,u*5));return `<div style="margin-top:9px"><div class="row-sub">${m} · ${u}명</div><div class="bar"><i style="width:${pct}%"></i></div></div>`;}).join('')}</div><div class="help" style="margin-top:8px">실제 운영에서는 12/26/52주 추세와 모임/Guest/Online/순모임 추세를 같은 구조로 제공합니다.</div>`; }
function individualReport(){ const m=db.members.find(x=>x.status==='Active')||db.members[0]; const rows=db.sessions.filter(s=>sessionAttendance(s.id).includes(m.id)).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20); return `<div class="card"><div class="row-title">개인 출석 · ${esc(displayName(m))} ${esc(m.title)}</div><div class="row-sub">날짜 / 모임 / 당시 부서 / 당시 분류</div><div class="table-wrap" style="margin-top:8px"><table class="table"><thead><tr><th>날짜</th><th>모임</th><th>출석</th><th>부서</th><th>분류</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${s.date}</td><td>${esc(meetingById(s.meetingId)?.name||s.meetingId)}</td><td>출석</td><td>${deptName(m.deptId)}</td><td>${classification(m,s.meetingId,s.date)}</td></tr>`).join('')}</tbody></table></div></div>`; }
function groupReport(){ const sessions=db.groupSessions.filter(s=>s.status!=='Cancelled'),byGroup=db.groups.filter(g=>g.status==='Active').map(g=>{const ss=sessions.filter(s=>s.groupId===g.id);let sum=0,c=0,children=0,guests=0;ss.forEach(s=>{const den=groupDenominator(s); if(den.length){sum+=s.attendance.filter(id=>den.includes(id)).length/den.length;c++;}children+=s.children||0;guests+=s.guests||0;});return {g,meetings:ss.length,rate:c?Math.round(sum/c*100):0,children,guests};}); return `<div class="grid three">${statCard(sessions.length,'순모임 회차','예배와 분리','main-number')}${statCard(new Set(sessions.flatMap(s=>s.attendance)).size,'순원 Unique','등록교인')}${statCard(sessions.reduce((n,s)=>n+(s.guests||0),0),'방문자','누계')}</div><section class="section"><div class="section-head"><h2>순별 요약</h2><div class="hint">순위 없음</div></div><div class="row-list">${byGroup.map(x=>`<div class="row-card"><div class="mini-icon">◉</div><div class="row-main"><div class="row-title">${esc(x.g.name)}</div><div class="row-sub">${x.meetings}회 · 순자녀들 ${x.children} · 방문 ${x.guests}</div><div class="bar"><i style="width:${x.rate}%"></i></div></div><div class="number" style="font-size:24px">${x.rate}%</div></div>`).join('')}</div></section>`; }

function morePage(){
  const adminGroups=isAdmin()?`<div><div class="menu-group-title">관리</div>${menuCard('meetings','모임 관리','정규 반복 · 기간형 · 일회성')}${menuCard('groups','순 관리','순원 배정 · 순장/부순장 · 회차')}${menuCard('users','사용자 / 권한','Admin · User · Google 계정')}</div><div><div class="menu-group-title">시스템</div>${menuCard('settings','기본정보 설정','교회 · 부서 · 직분 · 장소 · 기준')}${menuCard('backup','백업 / Restore','자동/수동 · 복원 안전백업')}${menuCard('archive','Archive','오래된 연도 읽기 전용')}${menuCard('audit','Audit Log','모든 변경 이력')}</div>`:'';
  return `<section class="section"><div class="section-head"><h2>더보기</h2><div class="hint">${isAdmin()?'Admin 관리':'사용자 설정'}</div></div><div class="menu-groups">${adminGroups}<div><div class="menu-group-title">화면</div>${menuCard('theme','테마',ui.theme==='dark'?'Dark':'Light',true)}${menuCard('font','글자 크기',ui.font==='large'?'크게':'기본',true)}${menuCard('reset','Demo 초기화','테스트 데이터 재생성',true)}</div></div></section>`;
}
function menuCard(page,title,sub,action=false){return `<div class="menu-card" ${action?`data-menu-action="${page}"`:`data-admin-page="${page}"`}><div><div class="menu-card-title">${title}</div><div class="menu-card-sub">${sub}</div></div><span class="chevron">›</span></div>`;}

function meetingsPage(){ if(!isAdmin())return denied(); return `<section class="section"><div class="section-head"><h2>모임 관리</h2><div class="toolbar-row"><button class="btn primary" id="addMeeting">+ 모임</button>${(ui.adminPage==='one-time')?'<button class="btn" id="unionService">연합예배 만들기</button>':''}</div></div><div class="tabs">${[['regular','정규 반복'],['period','기간형'],['one-time','일회성']].map(([t,l])=>`<button class="tab ${ui.adminPage===t||(!ui.adminPage&&t==='regular')?'on':''}" data-meeting-tab="${t}">${l}</button>`).join('')}</div><div class="row-list">${db.meetings.filter(m=>m.type===(ui.adminPage||'regular')).sort((a,b)=>(a.order||0)-(b.order||0)).map(meetingAdminRow).join('')||'<div class="empty">없음</div>'}</div></section>`; }
function meetingAdminRow(m){return `<div class="row-card" data-edit-meeting="${m.id}"><div class="mini-icon">${m.type==='one-time'?'★':m.type==='period'?'▣':'✧'}</div><div class="row-main"><div class="row-title">${esc(m.name)}</div><div class="row-sub">${m.status} · ${m.type==='regular'?'요일 '+m.weekdays.join(','):m.type==='period'?`${m.start} ~ ${m.end}`:m.date} · ${m.time||''} · ${locationName(m.locationId)}</div></div><span class="badge ${m.status==='Active'?'ok':m.status==='Archived'?'warn':''}">${m.status}</span></div>`; }

function groupsPage(){ if(!isAdmin())return denied(); return `<section class="section"><div class="section-head"><h2>순 관리</h2><button class="btn primary" id="addGroup">+ 순</button></div><div class="row-list">${db.groups.slice().sort((a,b)=>(a.status===b.status?nameSort({name:a.name},{name:b.name}):a.status==='Active'?-1:1)).map(g=>{const leader=memberById(g.leaderId);return `<div class="row-card" data-edit-group="${g.id}"><div class="mini-icon">◉</div><div class="row-main"><div class="row-title">${esc(g.name)}</div><div class="row-sub">${g.status} · 순원 ${groupMembers(g.id).length}명 · 순장 ${leader?esc(displayName(leader)):'미지정'} · 부순장 ${g.assistantIds.length}명</div></div><span class="chevron">›</span></div>`;}).join('')}</div><section class="section"><div class="section-head"><h2>순 미배정</h2><div class="hint">배정 가능 부서만</div></div><div class="row-list">${eligibleGroupMembers().filter(m=>!m.groupId).map(m=>memberRow(m,false)).join('')||'<div class="empty">없음</div>'}</div></section></section>`; }

function usersPage(){ if(!isAdmin())return denied(); return `<section class="section"><div class="section-head"><h2>사용자 / 권한</h2><button class="btn primary" id="addUser">+ 사용자</button></div><div class="row-list">${db.users.map(u=>`<div class="row-card" data-edit-user="${u.id}"><div class="avatar">@</div><div class="row-main"><div class="row-title">${esc(u.displayName)}</div><div class="row-sub">${esc(u.email)} · ${u.baseRole}${u.memberId?' · '+esc(displayName(memberById(u.memberId))):' · 외부 사용자'}</div></div><span class="badge ${u.status==='Active'?'ok':'warn'}">${u.status}</span></div>`).join('')}</div><div class="help" style="margin-top:8px">마지막 Active Admin은 비활성화할 수 없습니다. 한 Member에 여러 Google 계정 연결을 허용합니다.</div></section>`; }

function settingsPage(){ if(!isAdmin())return denied(); const c=db.config; return `<section class="section"><div class="section-head"><h2>기본정보 설정</h2><div class="hint">Admin</div></div><div class="card"><div class="form-grid two"><label><span class="field-label">교회명</span><input class="field" id="cfgChurch" value="${esc(c.church.name)}"></label><label><span class="field-label">Report 표시명</span><input class="field" id="cfgReportName" value="${esc(c.church.reportName)}"></label><label><span class="field-label">Time Zone</span><input class="field" id="cfgTZ" value="${esc(c.church.timezone)}"></label><label><span class="field-label">일반 User 과거 수정일</span><input class="field" type="number" id="cfgEditDays" value="${c.generalEditDays}"></label><label><span class="field-label">순 Note 조회/수정 기간</span><input class="field" type="number" id="cfgNoteDays" value="${c.groupNoteReadDays}"></label><label><span class="field-label">연속결석 표시 기준</span><input class="field" type="number" id="cfgAbsent" value="${c.absentAlertConsecutive}"></label><label><span class="field-label">정기 최근 회차</span><input class="field" type="number" id="cfgRegLookback" value="${c.thresholds.regularLookback}"></label><label><span class="field-label">정기 최소 출석</span><input class="field" type="number" id="cfgRegMin" value="${c.thresholds.regularMin}"></label><label><span class="field-label">장기결석 Lookback</span><input class="field" type="number" id="cfgLong" value="${c.thresholds.longLookback}"></label><label><span class="field-label">AUTO 전환 최소 회차</span><input class="field" type="number" id="cfgMinSessions" value="${c.thresholds.minSessions}"></label></div><button class="btn primary" id="saveSettings" style="margin-top:9px">설정 저장</button></div>${masterList('부서',db.departments,'department')}${masterList('직분',db.titles,'title')}${masterList('장소',db.locations,'location')}</section>`; }
function masterList(title,list,type){return `<section class="section"><div class="section-head"><h2>${title}</h2><button class="btn small" data-add-master="${type}">+ 추가</button></div><div class="row-list">${list.sort((a,b)=>a.order-b.order).map(x=>`<div class="row-card" data-edit-master="${type}|${x.id}"><div class="row-main"><div class="row-title">${esc(x.name)}</div><div class="row-sub">순서 ${x.order} · ${x.active?'Active':'Inactive'}</div></div><span class="badge ${x.active?'ok':'warn'}">${x.active?'사용':'중지'}</span></div>`).join('')}</div></section>`; }

function auditPage(){ if(!isAdmin())return denied(); return `<section class="section"><div class="section-head"><h2>Audit Log</h2><div class="hint">Admin only · ${db.audit.length}건</div></div><div class="form-grid two"><input class="search" id="auditQ" placeholder="사용자 / 성도 / 변경내용"><select class="field" id="auditType"><option value="">전체 유형</option><option>Attendance</option><option>Member</option><option>Group</option><option>Config</option><option>Backup</option><option>Report</option></select></div><div id="auditList" style="margin-top:8px">${renderAuditEntries(db.audit.slice(0,100))}</div></section>`; }
function renderAuditEntries(list){return list.map(a=>`<div class="audit-entry"><div class="audit-action">${esc(a.action)}</div><div class="audit-meta">${new Date(a.ts).toLocaleString('ko-KR')} · ${esc(a.actorName)} · ${esc(a.actorEmail)}</div><div class="audit-detail">${esc(a.detail)}</div></div>`).join('')||'<div class="empty">Audit 기록이 없습니다.</div>';}

function backupPage(){ if(!isAdmin())return denied(); return `<section class="section"><div class="section-head"><h2>백업 / Restore</h2><div class="hint">Demo Local Backup</div></div><div class="grid three">${smallStatus('Daily 보관',db.config.backup.daily+'개','설정')}${smallStatus('Weekly 보관',db.config.backup.weekly+'개','설정')}${smallStatus('Monthly 보관',db.config.backup.monthly+'개','설정')}</div><div class="toolbar-row" style="margin-top:8px"><button class="btn primary" id="makeBackup">수동 Backup</button><button class="btn" id="downloadBackup">JSON 다운로드</button><label class="btn" style="display:inline-flex;align-items:center"><input type="file" id="restoreFile" accept="application/json" style="display:none">Restore 파일 선택</label></div><div class="help" style="margin-top:8px">Restore 전에는 자동으로 pre-restore 안전백업을 생성합니다. 실제 배포에서는 자동/수동 백업과 선택 영역 Restore를 지원합니다.</div><section class="section"><div class="section-head"><h2>최근 Backup</h2></div><div class="row-list">${db.backups.slice(0,20).map(b=>`<div class="row-card"><div class="mini-icon">⧉</div><div class="row-main"><div class="row-title">${esc(b.label)}</div><div class="row-sub">${new Date(b.ts).toLocaleString('ko-KR')} · ${b.protected?'보호됨':'자동정리 대상'}</div></div><span class="badge">${b.type}</span></div>`).join('')||'<div class="empty">아직 Backup이 없습니다.</div>'}</div></section></section>`; }

function archivePage(){ if(!isAdmin())return denied(); const years=[...new Set(db.sessions.map(s=>Number(s.date.slice(0,4))))].sort((a,b)=>b-a); return `<section class="section"><div class="section-head"><h2>Archive / 연도별 자료</h2><div class="hint">${archiveCutoffYear}년 이하 읽기 전용</div></div><div class="row-list">${years.map(y=>{const ss=db.sessions.filter(s=>s.date.startsWith(String(y))),u=new Set(ss.flatMap(s=>sessionAttendance(s.id)));return `<div class="row-card" data-archive-year="${y}"><div class="mini-icon">${y<=archiveCutoffYear?'🔒':'▤'}</div><div class="row-main"><div class="row-title">${y}년</div><div class="row-sub">회차 ${ss.length} · 등록교인 Unique ${u.size}</div></div>${y<=archiveCutoffYear?'<span class="readonly">읽기 전용</span>':'<span class="badge ok">Active DB</span>'}</div>`;}).join('')}</div><div class="help" style="margin-top:8px">운영 설계상 오래된 연도는 Active DB에서 분리하여 Google 쪽 Archive 저장소에 보관하는 구조로 연결할 수 있습니다. 이 Test에서는 읽기 전용 정책을 시뮬레이션합니다.</div></section>`; }

function denied(){return '<div class="empty">이 기능은 Admin 권한이 필요합니다.</div>';}
