function openMemberModal(id){
  const m=id?memberById(id):null; const x=m||{id:'',name:'',title:'성도',deptId:'d_adult',note:'',groupId:'',status:'Active',joined:isoToday,suffix:'',overrides:{},initialClass:{sun2:'가끔'}};
  const hist=m?db.sessions.filter(s=>sessionAttendance(s.id).includes(m.id)).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8):[];
  openModal(m?'성도 상세 / 수정':'새 성도 추가',`<div class="form-grid two"><label><span class="field-label">이름</span><input class="field" id="mmName" value="${esc(x.name)}"></label><label><span class="field-label">직분</span><select class="field" id="mmTitle">${db.titles.filter(t=>t.active).map(t=>`<option ${x.title===t.name?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label><span class="field-label">부서</span><select class="field" id="mmDept">${db.departments.filter(d=>d.active).map(d=>`<option value="${d.id}" ${x.deptId===d.id?'selected':''}>${esc(d.name)}</option>`).join('')}</select></label><label><span class="field-label">상태</span><select class="field" id="mmStatus"><option ${x.status==='Active'?'selected':''}>Active</option><option ${x.status==='Inactive'?'selected':''}>Inactive</option><option ${x.status==='Deceased'?'selected':''}>Deceased</option></select></label><label><span class="field-label">순 ${isAdmin()?'':'(Admin만 변경)'}</span><select class="field" id="mmGroup" ${isAdmin()?'':'disabled'}><option value="">미배정</option>${db.groups.filter(g=>g.status==='Active').map(g=>`<option value="${g.id}" ${x.groupId===g.id?'selected':''}>${esc(g.name)}</option>`).join('')}</select></label><label><span class="field-label">등록/추적 시작일</span><input class="field" type="date" id="mmJoined" value="${x.joined}"></label></div><label style="display:block;margin-top:8px"><span class="field-label">Note</span><input class="field" id="mmNote" maxlength="200" value="${esc(x.note)}"></label>${m?`<section class="section"><div class="section-head"><h2>모임별 수동 분류</h2></div><div class="form-grid two">${regularMeetings().slice(0,4).map(mt=>`<label><span class="field-label">${esc(mt.name)}</span><select class="field" data-override="${mt.id}"><option value="AUTO" ${!m.overrides?.[mt.id]||m.overrides[mt.id]==='AUTO'?'selected':''}>AUTO (${classification(m,mt.id)})</option><option ${m.overrides?.[mt.id]==='정기'?'selected':''}>정기</option><option ${m.overrides?.[mt.id]==='가끔'?'selected':''}>가끔</option><option ${m.overrides?.[mt.id]==='장기'?'selected':''}>장기</option></select></label>`).join('')}</div></section><section class="section"><div class="section-head"><h2>최근 출석</h2><div class="hint">과거 수정은 권한/기간 적용</div></div><div class="row-list">${hist.map(s=>`<div class="row-card"><div class="row-main"><div class="row-title">${s.date} · ${esc(meetingById(s.meetingId)?.name||s.meetingId)}</div><div class="row-sub">당시 부서 ${deptName(m.deptId)} · ${classification(m,s.meetingId,s.date)}</div></div><span class="badge ok">출석</span></div>`).join('')||'<div class="empty">출석 기록 없음</div>'}</div></section>`:''}`,`<button class="btn" data-close-modal>취소</button><button class="btn primary" id="saveMemberModal">저장</button>`);
  $('#saveMemberModal').onclick=()=>saveMemberModal(m?.id); $$('[data-close-modal]').forEach(b=>b.onclick=closeModal);
}
function saveMemberModal(id){
  const name=$('#mmName').value.trim(); if(!name)return toast('이름을 입력하세요.','error');
  let m=id?memberById(id):{id:uid('m'),suffix:'',history:[],logins:[],overrides:{},initialClass:{sun2:'가끔'},joined:isoToday,status:'Active'}; const before=id?JSON.stringify(m):''; const oldGroup=m.groupId,oldStatus=m.status;
  Object.assign(m,{name,title:$('#mmTitle').value,deptId:$('#mmDept').value,status:$('#mmStatus').value,groupId:isAdmin()?$('#mmGroup').value:m.groupId,note:$('#mmNote').value.trim(),joined:$('#mmJoined').value||isoToday});
  if(!id)db.members.push(m); $$('[data-override]').forEach(s=>m.overrides[s.dataset.override]=s.value);
  if(['Inactive','Deceased'].includes(m.status)){m.groupId='';db.groups.forEach(g=>{if(g.leaderId===m.id)g.leaderId=null;g.assistantIds=g.assistantIds.filter(x=>x!==m.id);});}
  if(oldGroup&&oldGroup!==m.groupId){const og=groupById(oldGroup);if(og){if(og.leaderId===m.id)og.leaderId=null;og.assistantIds=og.assistantIds.filter(x=>x!==m.id);}}
  assignDuplicateSuffixes(db.members); m.history.unshift({ts:new Date().toISOString(),actor:currentActor().name,detail:id?'Member 수정':'Member 생성'});
  audit('Member',`${displayName(m)} ${id?'수정':'생성'}${oldGroup!==m.groupId?' · 순 변경':''}${oldStatus!==m.status?' · 상태 '+m.status:''}`,{memberId:m.id});saveDB();closeModal();render();
}

function openBulkModal(){openModal('선택 성도 일괄수정',`<div class="help">선택 ${ui.selectedMembers.length}명</div><div class="form-grid two" style="margin-top:8px"><label><span class="field-label">부서 변경</span><select class="field" id="bulkDept"><option value="">변경 안함</option>${db.departments.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></label><label><span class="field-label">상태 변경</span><select class="field" id="bulkStatus"><option value="">변경 안함</option><option>Active</option><option>Inactive</option><option>Deceased</option></select></label><label><span class="field-label">순 배정</span><select class="field" id="bulkGroup"><option value="__keep">변경 안함</option><option value="">미배정</option>${db.groups.filter(g=>g.status==='Active').map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select></label></div>`,`<button class="btn" data-close-modal>취소</button><button class="btn primary" id="applyBulk">적용</button>`);$('#applyBulk').onclick=()=>{const d=$('#bulkDept').value,st=$('#bulkStatus').value,g=$('#bulkGroup').value;ui.selectedMembers.forEach(id=>{const m=memberById(id);if(d)m.deptId=d;if(st)m.status=st;if(g!=='__keep')m.groupId=g;if(['Inactive','Deceased'].includes(m.status))m.groupId='';});audit('Member',`${ui.selectedMembers.length}명 일괄수정`);ui.selectedMembers=[];saveUI();saveDB();closeModal();render();};$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);}
function exportMembers(){const rows=[['Member ID','Name','Title','Department','Status','Small Group','Note'],...db.members.map(m=>[m.id,displayName(m),m.title,deptName(m.deptId),m.status,groupById(m.groupId)?.name||'',m.note])];downloadText(`members-${isoToday}.csv`,csv(rows),'text/csv;charset=utf-8');}

function openSessionOptions(){const s=ensureSession(ui.meetingId,ui.date);openModal('회차 설정',`<label><span class="field-label">회차 표시명 Override</span><input class="field" id="soName" value="${esc(s.nameOverride||'')}"></label><label class="checkline"><input type="checkbox" id="soExclude" ${s.excludeAuto?'checked':''}>자동 분류 계산에서 제외</label><label><span class="field-label">상태</span><select class="field" id="soStatus"><option ${s.status==='Held'?'selected':''}>Held</option><option ${s.status==='Cancelled'?'selected':''}>Cancelled</option></select></label>`,`<button class="btn" data-close-modal>취소</button><button class="btn primary" id="saveSessionOpt">저장</button>`);$('#saveSessionOpt').onclick=()=>{s.nameOverride=$('#soName').value.trim();s.excludeAuto=$('#soExclude').checked;s.status=$('#soStatus').value;audit('Config',`${meetingById(s.meetingId).name} ${s.date} 회차 설정 변경`,{meetingId:s.meetingId});saveDB();closeModal();render();};$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);}

function openGroupSessionModal(groupId,sessionId){const g=groupById(groupId),s=sessionId?groupSessionById(sessionId):null;openModal(`${esc(g.name)} 회차 ${s?'수정':'생성'}`,`<div class="form-grid two"><label><span class="field-label">날짜</span><input class="field" type="date" id="gsmDate" value="${s?.date||isoToday}"></label><label><span class="field-label">시간</span><input class="field" type="time" id="gsmTime" value="${s?.time||'18:30'}"></label></div><label style="display:block;margin-top:8px"><span class="field-label">장소 (자유입력)</span><input class="field" id="gsmLoc" value="${esc(s?.location||'')}"></label>${s?`<label style="display:block;margin-top:8px"><span class="field-label">상태</span><select class="field" id="gsmStatus"><option ${s.status==='Active'?'selected':''}>Active</option><option ${s.status==='Cancelled'?'selected':''}>Cancelled</option></select></label>`:''}`,`<button class="btn" data-close-modal>취소</button><button class="btn primary" id="saveGSM">저장</button>`);$('#saveGSM').onclick=()=>{if(s){s.date=$('#gsmDate').value;s.time=$('#gsmTime').value;s.location=$('#gsmLoc').value.trim();s.status=$('#gsmStatus').value;}else{const x={id:uid('gs'),groupId,date:$('#gsmDate').value,time:$('#gsmTime').value,location:$('#gsmLoc').value.trim(),status:'Active',note:'',noteUpdatedAt:'',noteUpdatedBy:'',rosterSnapshot:null,attendance:[],otherMembers:[],children:0,guests:0,createdBy:currentActor().name};db.groupSessions.push(x);ui.groupSessionId=x.id;}audit('Group',`${g.name} 회차 ${s?'수정':'생성'}`,{groupId});saveDB();closeModal();ui.page='group';saveUI();render();};$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);}

function openExclusionModal(){const s=currentGroupSession(),g=groupById(s.groupId);const members=groupMembers(g.id);openModal('순모임 출석 제외기간',`<div class="form-grid two"><label><span class="field-label">순원</span><select class="field" id="exMember">${members.map(m=>`<option value="${m.id}">${esc(displayName(m))}</option>`).join('')}</select></label><label><span class="field-label">사유 (앱에서만)</span><input class="field" id="exReason" placeholder="출장 / 한국 방문"></label><label><span class="field-label">시작</span><input class="field" type="date" id="exStart" value="${s.date}"></label><label><span class="field-label">종료</span><input class="field" type="date" id="exEnd" value="${addDays(s.date,7)}"></label></div><div class="help" style="margin-top:7px">겹치는 제외기간은 허용하지 않습니다. PDF/Excel에는 사유를 포함하지 않습니다.</div><div class="row-list" style="margin-top:8px">${db.exclusions.filter(e=>e.groupId===g.id).map(e=>`<div class="row-card"><div class="row-main"><div class="row-title">${esc(displayName(memberById(e.memberId)))}</div><div class="row-sub">${e.start} ~ ${e.end} · ${esc(e.reason)}</div></div></div>`).join('')||'<div class="empty">등록된 제외기간 없음</div>'}</div>`,`<button class="btn" data-close-modal>닫기</button><button class="btn primary" id="addExclusion">추가</button>`);$('#addExclusion').onclick=()=>{const memberId=$('#exMember').value,start=$('#exStart').value,end=$('#exEnd').value,reason=$('#exReason').value.trim();const overlap=db.exclusions.some(e=>e.groupId===g.id&&e.memberId===memberId&&!(end<e.start||start>e.end));if(overlap)return toast('기존 제외기간과 겹칩니다.','error');db.exclusions.push({id:uid('ex'),memberId,groupId:g.id,start,end,reason});audit('Group',`${displayName(memberById(memberId))} 제외기간 ${start}~${end}`,{groupId:g.id,memberId});saveDB();closeModal();render();};$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);}
function convertGuestToMember(){if(!isAdmin())return toast('Admin만 실제 교인으로 변환할 수 있습니다.','error');const s=currentGroupSession();const opts=activeMembers().filter(m=>m.groupId!==s.groupId).map(m=>`<option value="${m.id}">${esc(displayName(m))} · ${esc(groupById(m.groupId)?.name||'미배정')}</option>`).join('');openModal('방문 1명을 기타 등록회원으로 변환',`<select class="field" id="convertMember">${opts}</select><div class="help" style="margin-top:7px">방문자 수 -1, 기타 등록회원 +1. 원래 순 소속은 변경하지 않습니다.</div>`,`<button class="btn" data-close-modal>취소</button><button class="btn primary" id="doConvert">변환</button>`);$('#doConvert').onclick=()=>{if(s.guests<=0)return toast('변환할 방문자가 없습니다.','error');const id=$('#convertMember').value;s.guests--;s.otherMembers.push({memberId:id,originalGroupId:memberById(id).groupId||''});audit('Group',`방문자 → 기타 등록회원 ${displayName(memberById(id))}`,{groupId:s.groupId,memberId:id});saveDB();closeModal();render();};$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);}

function openUnionServiceModal(){
  const regs=regularMeetings();
  openModal('연합예배 만들기',`<label><span class="field-label">날짜</span><input class="field" type="date" id="usDate" value="${isoToday}"></label><label style="display:block;margin-top:8px"><span class="field-label">특별예배 이름</span><input class="field" id="usName" value="연합예배"></label><div class="field-label" style="margin-top:8px">취소할 기존 정규모임</div>${regs.map(m=>`<label class="checkline"><input type="checkbox" data-us-meeting="${m.id}" checked>${esc(m.name)}</label>`).join('')}<div class="help">선택된 기존 회차는 Cancelled 처리되고, 특별 연합예배가 별도 생성됩니다. 기존 모임 자동분류 출석으로 대체되지 않습니다.</div>`,`<button class="btn" data-close-modal>취소</button><button class="btn primary" id="saveUnion">생성</button>`);
  $('#saveUnion').onclick=()=>{const date=$('#usDate').value,name=$('#usName').value.trim()||'연합예배';const cancelled=[];$$('[data-us-meeting]:checked').forEach(c=>{const ss=ensureSession(c.dataset.usMeeting,date);ss.status='Cancelled';cancelled.push(c.dataset.usMeeting);});const id=uid('special');db.meetings.push({id,name,type:'one-time',status:'Active',date,time:'11:00',locationId:'loc_main',targetDepts:['d_adult','d_young','d_youth','d_child','d_toddler'],guest:true,online:false,order:35,note:'연합예배',baselineMeetings:cancelled});audit('Config',`${date} ${name} 생성 · 기존 ${cancelled.length}개 회차 취소`,{meetingId:id});saveDB();closeModal();ui.adminPage='one-time';render();};$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);
}
