'use strict';

const STORAGE_KEY = 'church_attendance_integrated_test_v1';
const UI_KEY = 'church_attendance_integrated_ui_v1';
const TODAY = new Date();
const isoToday = toISO(TODAY);
const currentYear = TODAY.getFullYear();
const archiveCutoffYear = currentYear - 2;
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const uid = (p='id') => `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const clamp0 = n => Math.max(0, Number(n || 0));
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const fmtDate = d => new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date(`${d}T12:00:00`));
const fmtShort = d => new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric'}).format(new Date(`${d}T12:00:00`));
const fmtMoney = n => new Intl.NumberFormat('en-US').format(n || 0);
function toISO(d){ const x=new Date(d); const y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),day=String(x.getDate()).padStart(2,'0'); return `${y}-${m}-${day}`; }
function addDays(date,delta){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+delta);return toISO(d)}
function weekday(date){return new Date(`${date}T12:00:00`).getDay()}
function startOfWeek(date){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()-d.getDay());return toISO(d)}
function endOfWeek(date){return addDays(startOfWeek(date),6)}
function monthKey(date){return String(date).slice(0,7)}
function sameMonth(a,b){return monthKey(a)===monthKey(b)}
function downloadText(filename,text,type='text/plain'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function csv(rows){return '\ufeff'+rows.map(r=>r.map(csvEscape).join(',')).join('\n')}
function seedData(){
 const depts=[{id:'d_adult',name:'장년부',active:true,order:1},{id:'d_young',name:'청년부',active:true,order:2},{id:'d_youth',name:'중고등부',active:true,order:3},{id:'d_child',name:'아동부',active:true,order:4},{id:'d_toddler',name:'영유아부',active:true,order:5}];
 const titles=['목사','전도사','장로','권사','집사','성도','학생'].map((name,i)=>({id:`t${i+1}`,name,active:true,order:i+1}));
 const locations=[{id:'loc_main',name:'본당',active:true,order:1},{id:'loc_vision',name:'비전홀',active:true,order:2},{id:'loc_fellow',name:'친교실',active:true,order:3},{id:'loc_class',name:'교육관',active:true,order:4}];
 const members=[['m1','김영수','집사','d_adult','출장 잦음','g_love','2024-01-01'],['m2','이선희','권사','d_adult','','g_love','2024-01-01'],['m3','박정호','집사','d_adult','','g_love','2024-03-01'],['m4','최미경','권사','d_adult','새가족 정착중','g_love','2025-05-01'],['m5','정수진','성도','d_young','','g_faith','2024-02-01'],['m6','한민수','집사','d_adult','','g_hope','2024-01-01'],['m7','오지혜','성도','d_young','해외 출장','g_faith','2024-01-01'],['m8','윤태호','집사','d_adult','','g_love','2024-01-01'],['m9','강은주','권사','d_adult','','g_hope','2024-01-01'],['m10','임성호','성도','d_adult','장기 출장','','2024-01-01'],['m11','송혜진','성도','d_young','','','2024-01-01'],['m12','조현우','학생','d_youth','','','2024-01-01'],['m13','배수민','학생','d_youth','','','2024-01-01'],['m14','문지훈','성도','d_adult','','g_love','2024-01-01'],['m15','서은영','집사','d_adult','','g_love','2024-01-01'],['m16','김영수','성도','d_young','동명이인','g_faith','2025-01-01'],['m17','홍길동','성도','d_adult','','g_hope','2025-10-01'],['m18','홍길동','집사','d_adult','새가족','g_hope','2026-01-15']].map((x,i)=>({id:x[0],name:x[1],title:x[2],deptId:x[3],note:x[4],groupId:x[5],joined:x[6],status:'Active',suffix:'',initialClass:{sun1:i%4===0?'가끔':'정기',sun2:i<10?'정기':(i<15?'가끔':'정기'),em:x[3]==='d_young'?'정기':'가끔'},overrides:{},logins:[],history:[]}));
 assignDuplicateSuffixes(members);
 const meetings=[{id:'dawn',name:'평일 새벽예배',type:'regular',status:'Active',weekdays:[1,2,3,4,5,6],time:'05:30',locationId:'loc_main',targetDepts:['d_adult','d_young'],guest:true,online:false,order:1,note:'월–토 새벽예배',thresholds:null},{id:'sun1',name:'주일 1부예배',type:'regular',status:'Active',weekdays:[0],time:'09:00',locationId:'loc_main',targetDepts:['d_adult','d_young'],guest:true,online:false,order:2,note:'',thresholds:null},{id:'sun2',name:'주일 2부예배',type:'regular',status:'Active',weekdays:[0],time:'11:00',locationId:'loc_main',targetDepts:['d_adult','d_young'],guest:true,online:true,order:3,note:'',thresholds:{regularLookback:4,regularMin:2,longLookback:30}},{id:'em',name:'EM 예배',type:'regular',status:'Active',weekdays:[0],time:'13:30',locationId:'loc_vision',targetDepts:['d_young','d_youth'],guest:true,online:true,order:4,note:'',thresholds:null},{id:'friday',name:'금요찬양예배',type:'regular',status:'Active',weekdays:[5],time:'19:30',locationId:'loc_main',targetDepts:['d_adult','d_young','d_youth'],guest:true,online:false,order:5,note:'',thresholds:null},{id:'bible26',name:'2026 봄 성경공부',type:'period',status:'Archived',start:'2026-02-01',end:'2026-05-15',weekdays:[3],time:'19:00',locationId:'loc_class',targetDepts:['d_adult'],guest:true,online:false,order:20,note:'12주 과정',classificationEnabled:false,participants:[{memberId:'m1',start:'2026-02-01',end:'2026-05-15'},{memberId:'m2',start:'2026-02-01',end:'2026-05-15'},{memberId:'m3',start:'2026-03-01',end:'2026-05-15'}],externalParticipants:[{id:'ext1',name:'James Lee',note:'친구 소개',start:'2026-02-01',end:'2026-05-15'}]},{id:'revival26',name:'2026 여름 부흥회',type:'one-time',status:'Active',date:isoToday,time:'19:00',locationId:'loc_main',targetDepts:['d_adult','d_young','d_youth'],guest:true,online:false,order:30,note:'전교인 특별집회',baselineMeetings:['sun1','sun2']}];
 const groups=[{id:'g_love',name:'사랑순',note:'장년 중심',status:'Active',leaderId:'m1',assistantIds:['m2'],order:1},{id:'g_faith',name:'믿음순',note:'청년/장년 혼합',status:'Active',leaderId:'m5',assistantIds:['m7'],order:2},{id:'g_hope',name:'소망순',note:'',status:'Active',leaderId:'m6',assistantIds:[],order:3},{id:'g_old',name:'은혜순',note:'종료된 순',status:'Inactive',leaderId:null,assistantIds:[],order:4}];
 const users=[{id:'u1',email:'admin@example.org',displayName:'김영수 집사',baseRole:'Admin',memberId:'m1',status:'Active'},{id:'u2',email:'user@example.org',displayName:'이선희 권사',baseRole:'User',memberId:'m2',status:'Active'},{id:'u3',email:'leader@example.org',displayName:'정수진 성도',baseRole:'User',memberId:'m5',status:'Active'},{id:'u4',email:'external@example.org',displayName:'재정부 Staff',baseRole:'User',memberId:null,status:'Inactive'}];
 const data={version:1,config:{church:{name:'한인교회',abbr:'KCC',address:'123 Church St, Houston, TX',phone:'713-555-0100',website:'www.example.org',reportName:'한인교회',timezone:'America/Chicago'},thresholds:{regularLookback:4,regularMin:2,longLookback:30,minSessions:4},generalEditDays:7,groupNoteReadDays:7,auditRetentionYears:2,eligibleGroupDepts:['d_adult','d_young'],absentAlertConsecutive:2,backup:{daily:14,weekly:12,monthly:12},theme:'dark'},departments:depts,titles,locations,members,meetings,groups,users,sessions:[],attendance:{},groupSessions:[],exclusions:[],audit:[],backups:[],archivedYears:[2023,2024],reportSaves:[]};
 generateHistoricalDemo(data);data.groupSessions.push({id:'gs_today_love',groupId:'g_love',date:isoToday,time:'18:30',location:'김영수 집사 가정',status:'Active',note:'박집사 다음 주 검사 예정. 함께 기도 부탁드립니다.',noteUpdatedAt:new Date().toISOString(),noteUpdatedBy:'김영수 집사',rosterSnapshot:null,attendance:['m1','m2','m3','m14'],otherMembers:[{memberId:'m9',originalGroupId:'g_hope'}],children:3,guests:1,createdBy:'김영수 집사'});data.exclusions.push({id:'ex1',memberId:'m8',groupId:'g_love',start:addDays(isoToday,-3),end:addDays(isoToday,10),reason:'한국 방문'});return data;
}
function assignDuplicateSuffixes(members){const map={};members.forEach(m=>(map[m.name]||=[]).push(m));Object.values(map).forEach(list=>{if(list.length>1)list.forEach((m,i)=>{if(!m.suffix)m.suffix=String.fromCharCode(65+i)})})}
function generateHistoricalDemo(data){const p={m1:[1,1,1,1,1,1,1,1],m2:[1,1,0,1,1,1,0,1],m3:[1,0,1,1,0,1,1,1],m4:[1,1,1,0,1,1,1,1],m5:[0,1,1,0,1,0,1,1],m6:[1,1,0,1,1,0,1,0],m7:[0,0,1,0,0,1,0,0],m8:[1,0,0,1,0,0,1,0],m9:[0,1,0,0,1,0,0,0],m10:[0,0,0,0,0,0,0,0],m11:[0,0,0,0,0,0,0,0],m14:[1,1,1,1,1,1,1,1],m15:[1,1,1,0,1,1,1,0],m16:[1,0,1,0,1,0,1,0],m17:[1,1,0,1,0,1,1,0],m18:[1,1,1,1,0,1,1,1]};const d=new Date(`${isoToday}T12:00:00`);d.setDate(d.getDate()-d.getDay());const sunday=toISO(d);for(let w=0;w<8;w++){const date=addDays(sunday,-7*w);['sun1','sun2','em'].forEach(mid=>{const sid=`${mid}_${date}`;data.sessions.push({id:sid,meetingId:mid,date,status:'Held',nameOverride:'',excludeAuto:false,guestCount:mid==='sun2'?2+w%3:1,onlineCount:mid==='sun2'?5+w%4:(mid==='em'?2:0),createdFromSchedule:true});const ids=[];data.members.forEach((m,idx)=>{let present=mid==='sun2'?!!p[m.id]?.[w]:mid==='sun1'?(idx+w)%4!==0&&['d_adult','d_young'].includes(m.deptId):m.deptId==='d_young'?(idx+w)%3!==0:(m.deptId==='d_youth'&&(idx+w)%2===0);if(present&&m.status==='Active')ids.push(m.id)});data.attendance[sid]=ids})}data.sessions.push({id:'sun2_2024-12-29',meetingId:'sun2',date:'2024-12-29',status:'Held',nameOverride:'송년주일',excludeAuto:false,guestCount:7,onlineCount:14,createdFromSchedule:true});data.attendance['sun2_2024-12-29']=['m1','m2','m3','m5','m6','m8','m9','m14','m15'];data.sessions.push({id:'sun2_2023-12-31',meetingId:'sun2',date:'2023-12-31',status:'Held',nameOverride:'송년주일',excludeAuto:false,guestCount:4,onlineCount:10,createdFromSchedule:true});data.attendance['sun2_2023-12-31']=['m1','m2','m3','m6','m14']}
let db=loadDB(),ui=loadUI();
function loadDB(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(x?.version===1)return x}catch{}const f=seedData();localStorage.setItem(STORAGE_KEY,JSON.stringify(f));return f}
function saveDB(){localStorage.setItem(STORAGE_KEY,JSON.stringify(db))}
function loadUI(){const d={page:'home',roleMode:'admin',font:'normal',theme:'dark',date:isoToday,meetingId:'sun2',attendanceFilter:'all',search:'',memberFilter:{dept:'',status:'Active',group:'',q:''},selectedMembers:[],longCollapsed:true,groupAdminId:'g_love',groupSessionId:'',reportTab:'weekly',reportMode:'summary',reportMeeting:'all',reportDept:'all',adminPage:'',classificationKey:'',classificationSnapshot:{}};try{return Object.assign(d,JSON.parse(localStorage.getItem(UI_KEY)||'{}'))}catch{return d}}
function saveUI(){localStorage.setItem(UI_KEY,JSON.stringify(ui))}
function currentActor(){if(ui.roleMode==='admin')return{name:'김영수 집사',email:'admin@example.org',role:'Admin',memberId:'m1'};if(ui.roleMode==='leader')return{name:'정수진 성도',email:'leader@example.org',role:'User + 순장/부순장',memberId:'m5'};return{name:'이선희 권사',email:'user@example.org',role:'User',memberId:'m2'}}
function isAdmin(){return ui.roleMode==='admin'}function isLeader(){return ui.roleMode==='leader'}function canAccessGroup(){return isAdmin()||isLeader()}function canEditGeneralDate(date){if(isAdmin())return true;if(isReadOnlyYear(date))return false;return date>isoToday||daysBetween(date,isoToday)<=db.config.generalEditDays}function canReadGroupNote(s){return isAdmin()||daysBetween(s.date,isoToday)<=db.config.groupNoteReadDays}function isReadOnlyYear(date){return Number(String(date).slice(0,4))<=archiveCutoffYear}function daysBetween(a,b){return Math.abs(Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/86400000))}function audit(action,detail,meta={}){const a=currentActor();db.audit.unshift({id:uid('aud'),ts:new Date().toISOString(),actorName:a.name,actorEmail:a.email,action,detail,meetingId:meta.meetingId||'',memberId:meta.memberId||'',groupId:meta.groupId||''});if(db.audit.length>2000)db.audit.length=2000;saveDB()}
function memberById(id){return db.members.find(x=>x.id===id)}function meetingById(id){return db.meetings.find(x=>x.id===id)}function groupById(id){return db.groups.find(x=>x.id===id)}function deptName(id){return db.departments.find(x=>x.id===id)?.name||'미지정'}function locationName(id){return db.locations.find(x=>x.id===id)?.name||''}function displayName(m){return `${m.name}${m.suffix?'-'+m.suffix:''}`}function activeMembers(){return db.members.filter(m=>m.status==='Active')}function eligibleGroupMembers(){return db.members.filter(m=>m.status==='Active'&&db.config.eligibleGroupDepts.includes(m.deptId))}function groupMembers(id){return db.members.filter(m=>m.status==='Active'&&m.groupId===id)}
function regularMeetings(){return db.meetings.filter(m=>m.type==='regular'&&m.status==='Active').sort((a,b)=>a.order-b.order)}function scheduledMeetings(date){const wd=weekday(date),r=regularMeetings().filter(m=>m.weekdays.includes(wd)),o=db.meetings.filter(m=>m.type==='one-time'&&m.status==='Active'&&m.date===date),p=db.meetings.filter(m=>m.type==='period'&&m.status==='Active'&&date>=m.start&&date<=m.end&&m.weekdays.includes(wd));return [...r,...p,...o].sort((a,b)=>(a.time||'').localeCompare(b.time||''))}function ensureSession(meetingId,date){let s=db.sessions.find(x=>x.meetingId===meetingId&&x.date===date);if(!s){s={id:`${meetingId}_${date}`,meetingId,date,status:'Held',nameOverride:'',excludeAuto:false,guestCount:0,onlineCount:0,createdFromSchedule:true};db.sessions.push(s);db.attendance[s.id]=[];saveDB()}return s}function sessionsForMeeting(id,before=isoToday){return db.sessions.filter(s=>s.meetingId===id&&s.date<=before&&s.status==='Held').sort((a,b)=>b.date.localeCompare(a.date))}function sessionAttendance(id){return db.attendance[id]||=([])}
function thresholdsFor(m){return Object.assign({},db.config.thresholds,m.thresholds||{})}function classification(member,meetingId,date=isoToday){const m=meetingById(meetingId);if(!m)return'가끔';if(m.type==='one-time'){const b=(m.baselineMeetings||[]).map(id=>classification(member,id,date));if(b.includes('정기'))return'정기';if(b.includes('가끔'))return'가끔';return'장기'}if(m.type==='period'&&!m.classificationEnabled)return'정기';const o=member.overrides?.[meetingId];if(o&&o!=='AUTO')return o;const th=thresholdsFor(m),ss=sessionsForMeeting(meetingId,date).filter(s=>!s.excludeAuto&&s.date>=member.joined).slice(0,th.longLookback);if(ss.length<th.minSessions)return member.initialClass?.[meetingId]||'가끔';const recent=ss.slice(0,th.regularLookback),hits=recent.reduce((n,s)=>n+(sessionAttendance(s.id).includes(member.id)?1:0),0);if(hits>=th.regularMin)return'정기';return ss.reduce((n,s)=>n+(sessionAttendance(s.id).includes(member.id)?1:0),0)>0?'가끔':'장기'}
function ensureClassificationSnapshot(mid,date){const key=`${mid}|${date}`;if(ui.classificationKey!==key){ui.classificationKey=key;ui.classificationSnapshot={};activeMembers().forEach(m=>ui.classificationSnapshot[m.id]=classification(m,mid,date));saveUI()}}function effectiveClass(m){return ui.classificationSnapshot[m.id]||classification(m,ui.meetingId,ui.date)}function consecutiveAbsences(id,mid,date=isoToday){let n=0;for(const s of sessionsForMeeting(mid,date)){if(sessionAttendance(s.id).includes(id))break;n++}return n}
function groupSessionById(id){return db.groupSessions.find(s=>s.id===id)}function todayGroupSessions(){return db.groupSessions.filter(s=>s.date===isoToday&&s.status!=='Cancelled')}function leaderGroup(){if(isAdmin())return db.groups.find(g=>g.id===ui.groupAdminId)||db.groups.find(g=>g.status==='Active');const a=currentActor();return db.groups.find(g=>g.status==='Active'&&(g.leaderId===a.memberId||g.assistantIds.includes(a.memberId)))||db.groups.find(g=>g.id==='g_faith')}function exclusionsFor(mid,gid,date){return db.exclusions.filter(e=>e.memberId===mid&&e.groupId===gid&&date>=e.start&&date<=e.end)}function lockGroupRoster(s){if(s.rosterSnapshot)return s.rosterSnapshot;s.rosterSnapshot=groupMembers(s.groupId).map(m=>m.id);saveDB();return s.rosterSnapshot}function groupDenominator(s){return lockGroupRoster(s).filter(id=>!exclusionsFor(id,s.groupId,s.date).length)}
